databases:
 - name: <project name>
   region: frankfurt
   databaseName: <project name>_db
   user: <project name>_backend

services:
 - type: web
   name: django-starter
   region: frankfurt
   branch: master
   healthCheckPath: /health
   env: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn <project name>.wsgi:application"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: <project name>
         property: connectionString
     - key: SECRET_KEY
       generateValue: true
     - key: WEB_CONCURRENCY
       value: 1
     - key: ENVIRONMENT
       value: production